package com.angelsushi.cds.error;

public enum ErrorType {

    CONVERT_INTEGER,
    NO_PLAYER_TEAM,
    ARGS_UNAVAILABLE,
    NOT_OP,
    NOT_ENOUGH_EMERALDS,
    ALREADY_EXIST_HOUSE,
    NOT_HOUSE_OWNER,
    NO_OFFER,
    NO_HOUSE,
    ALREADY_BUY,
    NOT_HOUSE_BUYER,
    IS_HOUSE_OWNER,
    NO_PLAYER,
    PLACE_BLOCK,
    BREAK_BLOCK,
    ALREADY_LEADERBOARD_EXIST,
    ALREADY_EXIST_TEAM,
    HAS_ALREADY_TEAM,
    NO_TEAM_CHIEF,
    NOT_INVITE,
    ALREADY_SEND_OFFER;
}
